import sys, pickle, warnings
sys.path.insert(0, r'e:\HalluDet\Hallu_Detect')
warnings.filterwarnings('ignore')
import numpy as np

# Check what the scaler was actually fitted on - what range of F2 did it see?
with open(r'e:\HalluDet\Hallu_Detect\models\meta_learner\feature_scaler.pkl','rb') as f:
    scaler = pickle.load(f)
print('StandardScaler params:')
print(f'  mean_  = {scaler.mean_}')
print(f'  scale_ = {scaler.scale_}')
print(f'  var_   = {scaler.var_}')
print()
print('Training F2 distribution tells us:')
print('  Factual range: 0.49-0.83, mean=0.66')
print('  Hallucin range: 0.17-0.83, mean=0.33')
print()
print('Scaler mean=0.408, scale=0.202')
print()
print('If demo inputs fall near 0.5-0.55 (both classes):')
print('  z-score = (0.50 - 0.408) / 0.202 = +0.455')
print('  z-score = (0.53 - 0.408) / 0.202 = +0.604')
print()
print('These z-scores are in the training distribution overlap zone,')
print('where MLP prediction is ambiguous (around 0.3-0.5 raw).')
print()
print('='*65)
print('THE FULL ROOT CAUSE CHAIN:')
print('='*65)
print()
print('1. TRAINING FEATURE COLLAPSE:')
print('   - Only ACTIVE_FEATURES=[2] (ens_mean_ent) used in MLP')
print('   - F0 (nli_ent) AUROC=0.985 -- abandoned as "OOD"')
print('   - F5 (rav_max_ent) AUROC=0.925 -- abandoned as "OOD"')
print('   - MLP is essentially a 1-feature classifier')
print()
print('2. TRAINING/INFERENCE DISTRIBUTION MISMATCH:')
print('   Training: ens_mean_ent range = 0.17-0.83')
print('     Factual mean=0.66, Hallucin mean=0.33 -> clear separation')
print('   Demo: ens_mean_ent range = ~0.50-0.55 for ALL claims')
print('     Because load_bart=False in demo, M3=0.5 fallback always')
print()  
print('3. THE CONSTANT OUTPUT:')
print('   When demo F2 = 0.50-0.53, MLP outputs 0.44-0.81 raw')
print('   Platt maps 0.44 -> 0.26, 0.81 -> 0.74')
print('   But in reality both factual AND hallucinated demo claims')
print('   have F2 near 0.50-0.55 -> same MLP output -> cant distinguish')
print()
print('4. WHY AUROC=0.98 IS FAKE:')
print('   Training data has clear F2 separation (0.33 vs 0.66)')
print('   Test AUROC is measured on same-distribution data')
print('   Demo claims are OOD - NLI model saturates near-zero entailment')
print('   The 0.0003 spread between factual/hallucinated is noise')
print()
print('5. ENSEMBLE REGRESSION BUG:')
print('   Adding more signals (RAV, ensemble) made AUROC WORSE because:')
print('   They introduced OOD calibration mismatch')
print('   The added features have different distributions at demo time')
print()
print('FIX STRATEGY:')
print('  - Use ALL 8 features in meta-learner (ACTIVE_FEATURES=[0,1,2,3,4,5,6,7])')
print('  - But RETRAIN with features matching demo inference conditions:')
print('    * load_bart=False means M3=0.5 in training too')
print('    * OR: load_bart=True at both training AND demo time')
print('  - Alternative: replace MLP with direct multi-signal score')
print('    that is robust to OOD')
